/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Forms.JPFrm.ConstanciaRentaJPFrm;
import Forms.JPFrm.ConstanciaSueldoJPFrm;
import Forms.JPFrm.agregarEmpleadoFrmI;
import Forms.JPFrm.agregarPagoJPFrm;
import Forms.JPFrm.dashboardFrmI;
import Forms.JPFrm.boletaPagoFrmI;
import com.sun.awt.AWTUtilities;
import java.awt.BorderLayout;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author luis
 */
public class DashboardForm extends javax.swing.JFrame {

    int anchoPanel = 952;
    int altoPanel = 650;
    public DashboardForm() {
        initComponents();
        
         AWTUtilities.setWindowOpaque(this, false);
        
        // Venta centrada al iniciar
        this.setLocationRelativeTo(null);
        
        // Redondear bordes de ventana
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 10, 4);
        AWTUtilities.setWindowShape(this, forma);
        
        // Asignar icono 
        setIconImage(new ImageIcon(getClass().getResource("/Assets/Icons/icono.png")).getImage());
        
        
        // Iniciar el dashboard
        dashboardFrmI dashFrm = new dashboardFrmI();
        dashFrm.setSize(anchoPanel, altoPanel);
        dashFrm.setLocation(0, 0);
        
        container_contenido.removeAll();
        container_contenido.add(dashFrm , BorderLayout.CENTER);
        container_contenido.revalidate();
        container_contenido.repaint();
        btn_home.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        btn_min = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_AgregarEmpleado = new javax.swing.JButton();
        btn_boletaPago = new javax.swing.JButton();
        btn_constanciaRenta = new javax.swing.JButton();
        btn_constanciaSueldo = new javax.swing.JButton();
        btn_agregarPago = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        container_contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000000, 10000));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 111, 212), 3, true));

        btn_min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_min.png"))); // NOI18N
        btn_min.setBorderPainted(false);
        btn_min.setContentAreaFilled(false);
        btn_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_min.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_min.setName(""); // NOI18N
        btn_min.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_min_hover.png"))); // NOI18N
        btn_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minActionPerformed(evt);
            }
        });

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_close.png"))); // NOI18N
        btn_close.setBorderPainted(false);
        btn_close.setContentAreaFilled(false);
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_close.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_close_hover.png"))); // NOI18N
        btn_close.setVerifyInputWhenFocusTarget(false);
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(100, 111, 212));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ContaSoft");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        btn_AgregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_agregarEmpleado.png"))); // NOI18N
        btn_AgregarEmpleado.setBorderPainted(false);
        btn_AgregarEmpleado.setContentAreaFilled(false);
        btn_AgregarEmpleado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_agregarEmpleadohover.png"))); // NOI18N
        btn_AgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarEmpleadoActionPerformed(evt);
            }
        });

        btn_boletaPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_BoletaPago.png"))); // NOI18N
        btn_boletaPago.setBorderPainted(false);
        btn_boletaPago.setContentAreaFilled(false);
        btn_boletaPago.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_BoletaPagohover.png"))); // NOI18N
        btn_boletaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boletaPagoActionPerformed(evt);
            }
        });

        btn_constanciaRenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_renta.png"))); // NOI18N
        btn_constanciaRenta.setBorderPainted(false);
        btn_constanciaRenta.setContentAreaFilled(false);
        btn_constanciaRenta.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_rentahover.png"))); // NOI18N
        btn_constanciaRenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_constanciaRentaActionPerformed(evt);
            }
        });

        btn_constanciaSueldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_sueldo.png"))); // NOI18N
        btn_constanciaSueldo.setBorderPainted(false);
        btn_constanciaSueldo.setContentAreaFilled(false);
        btn_constanciaSueldo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_sueldohover.png"))); // NOI18N
        btn_constanciaSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_constanciaSueldoActionPerformed(evt);
            }
        });

        btn_agregarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_agregarPago.png"))); // NOI18N
        btn_agregarPago.setBorderPainted(false);
        btn_agregarPago.setContentAreaFilled(false);
        btn_agregarPago.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_agregarPagohover.png"))); // NOI18N
        btn_agregarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarPagoActionPerformed(evt);
            }
        });

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_regresar.png"))); // NOI18N
        btn_regresar.setBorderPainted(false);
        btn_regresar.setContentAreaFilled(false);
        btn_regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_regresar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_regresarhover.png"))); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_home.png"))); // NOI18N
        btn_home.setBorderPainted(false);
        btn_home.setContentAreaFilled(false);
        btn_home.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_homehover.png"))); // NOI18N
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_AgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_boletaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_constanciaRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_constanciaSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_agregarPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btn_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_regresar)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_AgregarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_agregarPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_boletaPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_constanciaRenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_constanciaSueldo)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        container_contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout container_contenidoLayout = new javax.swing.GroupLayout(container_contenido);
        container_contenido.setLayout(container_contenidoLayout);
        container_contenidoLayout.setHorizontalGroup(
            container_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 952, Short.MAX_VALUE)
        );
        container_contenidoLayout.setVerticalGroup(
            container_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 951, Short.MAX_VALUE)
                        .addComponent(btn_min, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(container_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_close)
                    .addComponent(btn_min))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int x , y ;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_formMouseDragged

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btn_minActionPerformed

    private void btn_AgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarEmpleadoActionPerformed
        agregarEmpleadoFrmI empleadoFrm = null;
        try {
            empleadoFrm = new agregarEmpleadoFrmI();
        } catch (SQLException ex) {
            Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        empleadoFrm.setSize(anchoPanel, altoPanel);
        empleadoFrm.setLocation(0, 0);
        
        container_contenido.removeAll();
        container_contenido.add(empleadoFrm , BorderLayout.CENTER);
        container_contenido.revalidate();
        container_contenido.repaint();
        
        btn_home.setSelected(false);
        btn_agregarPago.setSelected(false);
        btn_boletaPago.setSelected(false);
        btn_constanciaRenta.setSelected(false);
        btn_constanciaSueldo.setSelected(false);
        btn_AgregarEmpleado.setSelected(true);
        
    }//GEN-LAST:event_btn_AgregarEmpleadoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btn_boletaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boletaPagoActionPerformed
        boletaPagoFrmI boletaFrm = new boletaPagoFrmI();
        boletaFrm.setSize(anchoPanel, altoPanel);
        boletaFrm.setLocation(0, 0);
        
        container_contenido.removeAll();
        container_contenido.add(boletaFrm , BorderLayout.CENTER);
        container_contenido.revalidate();
        container_contenido.repaint();
        
        btn_home.setSelected(false);
        btn_agregarPago.setSelected(false);
        btn_boletaPago.setSelected(true);
        btn_constanciaRenta.setSelected(false);
        btn_constanciaSueldo.setSelected(false);
        btn_AgregarEmpleado.setSelected(false);
    }//GEN-LAST:event_btn_boletaPagoActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        MainForm mainFrm = new MainForm();
        mainFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // Iniciar el dashboard
        dashboardFrmI dashFrm = new dashboardFrmI();
        dashFrm.setSize(anchoPanel, altoPanel);
        dashFrm.setLocation(0, 0);
        
        container_contenido.removeAll();
        container_contenido.add(dashFrm , BorderLayout.CENTER);
        container_contenido.revalidate();
        container_contenido.repaint();
        
        btn_home.setSelected(true);
        btn_agregarPago.setSelected(false);
        btn_boletaPago.setSelected(false);
        btn_constanciaRenta.setSelected(false);
        btn_constanciaSueldo.setSelected(false);
        btn_AgregarEmpleado.setSelected(false);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_agregarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarPagoActionPerformed


        agregarPagoJPFrm agregarPagoFrm = new agregarPagoJPFrm();
        agregarPagoFrm.setSize(anchoPanel, altoPanel);
        agregarPagoFrm.setLocation(0, 0);
        
        container_contenido.removeAll();
        container_contenido.add(agregarPagoFrm , BorderLayout.CENTER);
        container_contenido.revalidate();
        container_contenido.repaint();
        
        
        btn_home.setSelected(false);
        btn_agregarPago.setSelected(true);
        btn_boletaPago.setSelected(false);
        btn_constanciaRenta.setSelected(false);
        btn_constanciaSueldo.setSelected(false);
        btn_AgregarEmpleado.setSelected(false);
    }//GEN-LAST:event_btn_agregarPagoActionPerformed

    private void btn_constanciaRentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_constanciaRentaActionPerformed
        
        ConstanciaRentaJPFrm constanciaRentaFrm = new ConstanciaRentaJPFrm();
        constanciaRentaFrm.setSize(anchoPanel, altoPanel);
        constanciaRentaFrm.setLocation(0, 0);
        
        container_contenido.removeAll();
        container_contenido.add(constanciaRentaFrm , BorderLayout.CENTER);
        container_contenido.revalidate();
        container_contenido.repaint();
        
        btn_home.setSelected(false);
        btn_agregarPago.setSelected(false);
        btn_boletaPago.setSelected(false);
        btn_constanciaRenta.setSelected(true);
        btn_constanciaSueldo.setSelected(false);
        btn_AgregarEmpleado.setSelected(false);
    }//GEN-LAST:event_btn_constanciaRentaActionPerformed

    private void btn_constanciaSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_constanciaSueldoActionPerformed
        
        ConstanciaSueldoJPFrm constancia_sueldoFrm = new ConstanciaSueldoJPFrm();
        constancia_sueldoFrm.setSize(anchoPanel, altoPanel);
        constancia_sueldoFrm.setLocation(0, 0);
        
        container_contenido.removeAll();
        container_contenido.add(constancia_sueldoFrm , BorderLayout.CENTER);
        container_contenido.revalidate();
        container_contenido.repaint();
        
        btn_home.setSelected(false);
        btn_agregarPago.setSelected(false);
        btn_boletaPago.setSelected(false);
        btn_constanciaRenta.setSelected(false);
        btn_constanciaSueldo.setSelected(true);
        btn_AgregarEmpleado.setSelected(false);
    }//GEN-LAST:event_btn_constanciaSueldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_AgregarEmpleado;
    private javax.swing.JButton btn_agregarPago;
    private javax.swing.JButton btn_boletaPago;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_constanciaRenta;
    private javax.swing.JButton btn_constanciaSueldo;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_min;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JPanel container_contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
