/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.Empleado;
import Clases.Impuesto;
import java.text.ParseException;
import java.time.LocalDate;
import java.text.SimpleDateFormat;  
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date; 
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mario
 */
public class ProcessForm extends javax.swing.JFrame {

    /**
     * Creates new form ProcessForm
     */
    Impuesto impuesto;
    LocalDate fecha_hoy;
    DefaultTableModel model;
    public ProcessForm() {
        initComponents();
  
        impuesto = new Impuesto();
        model = new DefaultTableModel();
        //Para extraer la fecha de la pc
        fecha_hoy = LocalDate.now();
        
        
        this.jcbMesVacaciones.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jlNombre = new javax.swing.JLabel();
        jlCargo = new javax.swing.JLabel();
        jtCargo = new javax.swing.JTextField();
        jlPeriodoPago = new javax.swing.JLabel();
        jcbPeriodoPago = new javax.swing.JComboBox<>();
        jlPeriodoPago1 = new javax.swing.JLabel();
        jftSueldo = new javax.swing.JFormattedTextField();
        jlPeriodoPago2 = new javax.swing.JLabel();
        jlPeriodoPago3 = new javax.swing.JLabel();
        jcbMesVacaciones = new javax.swing.JComboBox<>();
        jDateAñoContrato = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos del empleado");

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jlNombre.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jlNombre.setText("Nombre:");

        jlCargo.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jlCargo.setText("Cargo:");

        jtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCargoActionPerformed(evt);
            }
        });

        jlPeriodoPago.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jlPeriodoPago.setText("Periodo de pago:");

        jcbPeriodoPago.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jcbPeriodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensual", "Quincenal", "Semanal" }));

        jlPeriodoPago1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jlPeriodoPago1.setText("Sueldo:");

        jftSueldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        jftSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftSueldoActionPerformed(evt);
            }
        });

        jlPeriodoPago2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jlPeriodoPago2.setText("Fecha de contrato:");

        jlPeriodoPago3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jlPeriodoPago3.setText("Mes de vacaciones:");

        jcbMesVacaciones.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jcbMesVacaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jcbMesVacaciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jcbMesVacacionesMouseDragged(evt);
            }
        });
        jcbMesVacaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcbMesVacacionesMouseEntered(evt);
            }
        });
        jcbMesVacaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMesVacacionesActionPerformed(evt);
            }
        });

        jDateAñoContrato.setDateFormatString("MM/dd/yyyy");
        jDateAñoContrato.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jDateAñoContratoComponentRemoved(evt);
            }
        });
        jDateAñoContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateAñoContratoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDateAñoContratoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jDateAñoContratoMouseExited(evt);
            }
        });
        jDateAñoContrato.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateAñoContratoPropertyChange(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Calcular renta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlPeriodoPago3)
                                .addGap(2, 2, 2)
                                .addComponent(jcbMesVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jlPeriodoPago1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlPeriodoPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jcbPeriodoPago, 0, 170, Short.MAX_VALUE)
                                        .addComponent(jtCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                        .addComponent(jtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                        .addComponent(jftSueldo)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlPeriodoPago2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(jDateAñoContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCargo)
                            .addComponent(jtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPeriodoPago)
                            .addComponent(jcbPeriodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPeriodoPago1)
                            .addComponent(jftSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlPeriodoPago2)
                            .addComponent(jDateAñoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPeriodoPago3)
                            .addComponent(jcbMesVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCargoActionPerformed

    private void jftSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftSueldoActionPerformed

    private void jDateAñoContratoComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jDateAñoContratoComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateAñoContratoComponentRemoved

    private void jDateAñoContratoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateAñoContratoMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jDateAñoContratoMouseEntered

    private void jcbMesVacacionesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbMesVacacionesMouseDragged
        // TODO add your handling code here
    }//GEN-LAST:event_jcbMesVacacionesMouseDragged

    private void jcbMesVacacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbMesVacacionesMouseEntered
        // TODO add your handling code here:
            try {
                //Sacamos la fecha en formato MM/dd/yyy
                String fecha_inicio, fecha_actual;
                fecha_inicio = this.fecha_hoy.getMonthValue()+"/"+this.fecha_hoy.getDayOfMonth()+"/"+this.fecha_hoy.getYear();
                fecha_actual = (this.jDateAñoContrato.getCalendar().get(Calendar.MONTH)+1)+"/"+this.jDateAñoContrato.getCalendar().get(Calendar.DAY_OF_MONTH)+"/"+this.jDateAñoContrato.getCalendar().get(Calendar.YEAR);
                
                //Formateamos de string a Date las fechas con ayuda del SimpleDateFormat
                SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy", Locale.ENGLISH);
                Date firstDate = sdf.parse(fecha_actual);
                Date secondDate = sdf.parse(fecha_inicio);
                
                //Restamos las fechas
                long diff = secondDate.getTime() - firstDate.getTime();
                TimeUnit time = TimeUnit.DAYS; 
                long tiempo_laborado = time.convert(diff, TimeUnit.MILLISECONDS);
      
                //validamos si tiene derecho a vacaciones o no para habilitar el campo de las mismas
                if(tiempo_laborado >= 365){
                    this.jcbMesVacaciones.setEnabled(true);
                }
                else{
                    this.jcbMesVacaciones.setEnabled(false);
                }
            } catch (ParseException ex) {
                Logger.getLogger(ProcessForm.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jcbMesVacacionesMouseEntered

    private void jcbMesVacacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMesVacacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMesVacacionesActionPerformed

    private void jDateAñoContratoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateAñoContratoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateAñoContratoPropertyChange

    private void jDateAñoContratoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateAñoContratoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateAñoContratoMouseExited

    private void jDateAñoContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateAñoContratoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateAñoContratoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.asignacion_valor_variables();
        this.calculo_renta();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void asignacion_valor_variables(){
        this.impuesto.setNombre(this.jtNombre.getText().trim().toUpperCase());
        this.impuesto.setCargo(this.jtCargo.getText().trim().toLowerCase());
        this.impuesto.setPeriodo_Pago(this.jcbPeriodoPago.getSelectedItem().toString());
        
        this.impuesto.setSueldo(1500); //solo para prueba
        
//        this.empleado.setSueldo(Double.parseDouble(this.jftSueldo.getText().trim())); este no debe de llevar coma al momentode pasar de mil porque da error al convertir a double
        this.impuesto.setAnio_contrato(this.jDateAñoContrato.getDate()); //REVISIOn
        this.impuesto.setPago_Extra(this.jcbMesVacaciones.getSelectedItem().toString());//REVISIOn
    }
    public void calculo_renta(){
        //LOS PROCESOS DE LA CLASE IMPUESTOS YA APLICADOS AL FORM Y AGREGADOS A LA TAbLA
        
        //columnas de la tabla
        this.model.setNumRows(0);
        String[] nombreColum = {"Mes", "Remuneraciones grabadas", "Retención Mensual"};
        model.setColumnIdentifiers(nombreColum);
        
        //solo para ejemplo de llenado de la tabla
        String mes = "enero";
        this.impuesto.calculo_afp();
        this.impuesto.calculo_isss();
        this.impuesto.sueldo_sin_renta();
        model.addRow(new Object[]{mes, this.impuesto.getSueldo_noImpuesto(), 155.55}); //aqui debe agreguarse lo de cada mes
        
        
        this.jTable1.setModel(model);
        this.jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        this.jTable1.setFillsViewportHeight(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcessForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcessForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcessForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcessForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcessForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateAñoContrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbMesVacaciones;
    private javax.swing.JComboBox<String> jcbPeriodoPago;
    private javax.swing.JFormattedTextField jftSueldo;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlPeriodoPago;
    private javax.swing.JLabel jlPeriodoPago1;
    private javax.swing.JLabel jlPeriodoPago2;
    private javax.swing.JLabel jlPeriodoPago3;
    private javax.swing.JTextField jtCargo;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
