/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.JPFrm;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author luis
 */
public class agregarEmpleadoFrmI extends javax.swing.JPanel {

    /**
     * Creates new form agregarEmpleadoFrmI
     */
    public agregarEmpleadoFrmI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePicker = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        primerNombre_input = new Helpers.TextField();
        segundoNombre_input = new Helpers.TextField();
        lblDatosPersonales = new javax.swing.JLabel();
        primerApellido_input = new Helpers.TextField();
        segundoApellido_input = new Helpers.TextField();
        periodo_input = new Helpers.Combobox();
        lblDatosLaborales = new javax.swing.JLabel();
        cargo_input = new Helpers.TextField();
        salario_input = new Helpers.TextField();
        fechaContrato_input = new Helpers.TextField();
        vacaiones_input = new Helpers.Combobox();
        NIT_input = new Helpers.TextField();
        btn_agregarEmpleado = new javax.swing.JButton();
        btn_limpiarDatos = new javax.swing.JButton();

        datePicker.setForeground(new java.awt.Color(102, 102, 255));
        datePicker.setTextRefernce(fechaContrato_input);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(891, 604));
        setPreferredSize(new java.awt.Dimension(891, 604));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label_title.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        label_title.setText("Agregar Empleado");

        primerNombre_input.setForeground(new java.awt.Color(102, 102, 102));
        primerNombre_input.setToolTipText("Primer Nombre");
        primerNombre_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        primerNombre_input.setLabelText("Primer nombre");

        segundoNombre_input.setForeground(new java.awt.Color(102, 102, 102));
        segundoNombre_input.setToolTipText("Segundo nombre");
        segundoNombre_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        segundoNombre_input.setLabelText("Segundo nombre");

        lblDatosPersonales.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDatosPersonales.setForeground(new java.awt.Color(102, 102, 102));
        lblDatosPersonales.setText("Datos personales");

        primerApellido_input.setForeground(new java.awt.Color(102, 102, 102));
        primerApellido_input.setToolTipText("Primer apellido");
        primerApellido_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        primerApellido_input.setLabelText("Primer apellido");

        segundoApellido_input.setForeground(new java.awt.Color(102, 102, 102));
        segundoApellido_input.setToolTipText("Segundo apellido");
        segundoApellido_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        segundoApellido_input.setLabelText("Segundo apellido");

        periodo_input.setForeground(new java.awt.Color(102, 102, 102));
        periodo_input.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semanal", "Quincenal", "Mensual" }));
        periodo_input.setSelectedIndex(-1);
        periodo_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        periodo_input.setLabeText("Periodo de pago");

        lblDatosLaborales.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDatosLaborales.setForeground(new java.awt.Color(102, 102, 102));
        lblDatosLaborales.setText("Datos laborales");

        cargo_input.setForeground(new java.awt.Color(102, 102, 102));
        cargo_input.setToolTipText("Cargo");
        cargo_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cargo_input.setLabelText("Puesto o cargo");

        salario_input.setForeground(new java.awt.Color(102, 102, 102));
        salario_input.setToolTipText("Sueldo");
        salario_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        salario_input.setLabelText("Salario");

        fechaContrato_input.setForeground(new java.awt.Color(102, 102, 102));
        fechaContrato_input.setToolTipText("Fecha de contrato");
        fechaContrato_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        fechaContrato_input.setLabelText("Fecha de contrato");

        vacaiones_input.setForeground(new java.awt.Color(102, 102, 102));
        vacaiones_input.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));
        vacaiones_input.setSelectedIndex(-1);
        vacaiones_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        vacaiones_input.setLabeText("Mes de vacaciones");

        NIT_input.setForeground(new java.awt.Color(102, 102, 102));
        NIT_input.setText("0000-000000-000-0");
        NIT_input.setToolTipText("Cargo");
        NIT_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NIT_input.setLabelText("NIT");

        btn_agregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/btn_agregarEmpleadoDB.png"))); // NOI18N
        btn_agregarEmpleado.setBorderPainted(false);
        btn_agregarEmpleado.setContentAreaFilled(false);

        btn_limpiarDatos.setBackground(new java.awt.Color(255, 102, 102));
        btn_limpiarDatos.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btn_limpiarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiarDatos.setText("Limpiar datos");
        btn_limpiarDatos.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDatosPersonales)
                        .addContainerGap(650, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDatosLaborales)
                                .addComponent(vacaiones_input, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                .addComponent(salario_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(primerNombre_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(primerApellido_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cargo_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_agregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(segundoApellido_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(segundoNombre_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(periodo_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaContrato_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NIT_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_limpiarDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_title)
                .addGap(18, 18, 18)
                .addComponent(lblDatosPersonales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(primerNombre_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(primerApellido_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDatosLaborales)
                        .addGap(18, 18, 18)
                        .addComponent(cargo_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salario_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vacaiones_input, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(fechaContrato_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(segundoNombre_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(segundoApellido_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(periodo_input, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(NIT_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_agregarEmpleado)
                    .addComponent(btn_limpiarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Helpers.TextField NIT_input;
    private javax.swing.JButton btn_agregarEmpleado;
    private javax.swing.JButton btn_limpiarDatos;
    private Helpers.TextField cargo_input;
    private com.raven.datechooser.DateChooser datePicker;
    private Helpers.TextField fechaContrato_input;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel lblDatosLaborales;
    private javax.swing.JLabel lblDatosPersonales;
    private Helpers.Combobox periodo_input;
    private Helpers.TextField primerApellido_input;
    private Helpers.TextField primerNombre_input;
    private Helpers.TextField salario_input;
    private Helpers.TextField segundoApellido_input;
    private Helpers.TextField segundoNombre_input;
    private Helpers.Combobox vacaiones_input;
    // End of variables declaration//GEN-END:variables
}
