/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.JPFrm;

import javax.swing.BorderFactory;

/**
 *
 * @author luis
 */
public class agregarEmpleadoFrmI extends javax.swing.JPanel {

    /**
     * Creates new form agregarEmpleadoFrmI
     */
    public agregarEmpleadoFrmI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePicker = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        primerNombre_input = new Helpers.TextField();
        segundoNombre_input = new Helpers.TextField();
        lblDatosPersonales = new javax.swing.JLabel();
        primerApellido_input = new Helpers.TextField();
        segundoApellido_input = new Helpers.TextField();
        combobox1 = new Helpers.Combobox();
        lblDatosLaborales = new javax.swing.JLabel();
        primerApellido_input1 = new Helpers.TextField();
        primerApellido_input2 = new Helpers.TextField();
        fecha_contrato = new Helpers.TextField();
        jCheckBoxCustom1 = new Helpers.JCheckBoxCustom();
        lblDatosLaborales1 = new javax.swing.JLabel();
        sueldoExtra_input = new Helpers.TextField();
        combobox2 = new Helpers.Combobox();

        datePicker.setForeground(new java.awt.Color(102, 102, 255));
        datePicker.setTextRefernce(fecha_contrato);

        setMaximumSize(new java.awt.Dimension(891, 604));
        setPreferredSize(new java.awt.Dimension(891, 604));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label_title.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        label_title.setText("Agregar Empleado");

        primerNombre_input.setForeground(new java.awt.Color(102, 102, 102));
        primerNombre_input.setToolTipText("Primer Nombre");
        primerNombre_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        primerNombre_input.setLabelText("Primer nombre");

        segundoNombre_input.setForeground(new java.awt.Color(102, 102, 102));
        segundoNombre_input.setToolTipText("Segundo nombre");
        segundoNombre_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        segundoNombre_input.setLabelText("Segundo nombre");

        lblDatosPersonales.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDatosPersonales.setForeground(new java.awt.Color(102, 102, 102));
        lblDatosPersonales.setText("Datos personales");

        primerApellido_input.setForeground(new java.awt.Color(102, 102, 102));
        primerApellido_input.setToolTipText("Primer apellido");
        primerApellido_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        primerApellido_input.setLabelText("Primer apellido");

        segundoApellido_input.setForeground(new java.awt.Color(102, 102, 102));
        segundoApellido_input.setToolTipText("Segundo apellido");
        segundoApellido_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        segundoApellido_input.setLabelText("Segundo apellido");

        combobox1.setForeground(new java.awt.Color(102, 102, 102));
        combobox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semanal", "Quincenal", "Mensual" }));
        combobox1.setSelectedIndex(-1);
        combobox1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        combobox1.setLabeText("Periodo de pago");

        lblDatosLaborales.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDatosLaborales.setForeground(new java.awt.Color(102, 102, 102));
        lblDatosLaborales.setText("Datos laborales");

        primerApellido_input1.setForeground(new java.awt.Color(102, 102, 102));
        primerApellido_input1.setToolTipText("Cargo");
        primerApellido_input1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        primerApellido_input1.setLabelText("Puesto o cargo");

        primerApellido_input2.setForeground(new java.awt.Color(102, 102, 102));
        primerApellido_input2.setToolTipText("Sueldo");
        primerApellido_input2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        primerApellido_input2.setLabelText("Sueldo");

        fecha_contrato.setForeground(new java.awt.Color(102, 102, 102));
        fecha_contrato.setToolTipText("Fecha de contrato");
        fecha_contrato.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        fecha_contrato.setLabelText("Fecha de contrato");

        jCheckBoxCustom1.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBoxCustom1.setText("Servicios profesionales");
        jCheckBoxCustom1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCustom1ActionPerformed(evt);
            }
        });

        lblDatosLaborales1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDatosLaborales1.setForeground(new java.awt.Color(102, 102, 102));
        lblDatosLaborales1.setText("Datos extras");

        sueldoExtra_input.setForeground(new java.awt.Color(102, 102, 102));
        sueldoExtra_input.setToolTipText("Sueldo");
        sueldoExtra_input.setDisabledTextColor(new java.awt.Color(248, 248, 248));
        sueldoExtra_input.setEnabled(false);
        sueldoExtra_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        sueldoExtra_input.setLabelText("Sueldo extra");

        combobox2.setForeground(new java.awt.Color(102, 102, 102));
        combobox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semanal", "Quincenal", "Mensual" }));
        combobox2.setSelectedIndex(-1);
        combobox2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        combobox2.setLabeText("Mes de vacaciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatosLaborales1)
                            .addComponent(label_title)
                            .addComponent(lblDatosPersonales))
                        .addContainerGap(503, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sueldoExtra_input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combobox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(primerApellido_input1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblDatosLaborales)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(primerApellido_input2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(primerNombre_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(primerApellido_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(segundoApellido_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(segundoNombre_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_contrato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_title)
                .addGap(18, 18, 18)
                .addComponent(lblDatosPersonales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(primerNombre_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(primerApellido_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDatosLaborales)
                        .addGap(18, 18, 18)
                        .addComponent(primerApellido_input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(primerApellido_input2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(segundoNombre_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(segundoApellido_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fecha_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(combobox2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblDatosLaborales1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sueldoExtra_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCustom1ActionPerformed
        boolean estado = this.sueldoExtra_input.isEnabled();
        
        if(estado ==  false){
            this.sueldoExtra_input.setEnabled(true);
        }else{
            this.sueldoExtra_input.setEnabled(false);
        }
        
    }//GEN-LAST:event_jCheckBoxCustom1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Helpers.Combobox combobox1;
    private Helpers.Combobox combobox2;
    private com.raven.datechooser.DateChooser datePicker;
    private Helpers.TextField fecha_contrato;
    private Helpers.JCheckBoxCustom jCheckBoxCustom1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel lblDatosLaborales;
    private javax.swing.JLabel lblDatosLaborales1;
    private javax.swing.JLabel lblDatosPersonales;
    private Helpers.TextField primerApellido_input;
    private Helpers.TextField primerApellido_input1;
    private Helpers.TextField primerApellido_input2;
    private Helpers.TextField primerNombre_input;
    private Helpers.TextField segundoApellido_input;
    private Helpers.TextField segundoNombre_input;
    private Helpers.TextField sueldoExtra_input;
    // End of variables declaration//GEN-END:variables
}
