/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.JPFrm;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import Conexion.Conexion;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import Clases.*;
/**
 *
 * @author luis
 */
public class dashboardFrmI extends javax.swing.JPanel {

    int anchoPanel = 952;
    int altoPanel = 650;
    Conexion conn;
    ResultSet rs;
    scripts sc;
    
    public dashboardFrmI() {
        initComponents();
        conn = new Conexion();
        rs = null;
        sc = new scripts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_limpiarDatos = new javax.swing.JButton();
        btn_generarPDF = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        materialTabbed1 = new Helpers.MaterialTabbed();
        dashPane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        plantillaPatronalPane = new javax.swing.JPanel();
        nit_input = new Helpers.TextField();
        btn_limpiarDatos1 = new javax.swing.JButton();
        btn_generarPDF1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        btn_limpiarDatos.setBackground(new java.awt.Color(255, 102, 102));
        btn_limpiarDatos.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btn_limpiarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiarDatos.setText("Limpiar datos");
        btn_limpiarDatos.setBorder(null);
        btn_limpiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarDatosActionPerformed(evt);
            }
        });

        btn_generarPDF.setBackground(new java.awt.Color(153, 153, 255));
        btn_generarPDF.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btn_generarPDF.setForeground(new java.awt.Color(255, 255, 255));
        btn_generarPDF.setText("Generar PDF");
        btn_generarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarPDFActionPerformed(evt);
            }
        });

        setMaximumSize(new java.awt.Dimension(891, 604));
        setPreferredSize(new java.awt.Dimension(891, 604));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setText("Bienvenido al sistema ContaSoft");

        materialTabbed1.setBackground(new java.awt.Color(255, 255, 255));
        materialTabbed1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        dashPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel4.setText("Acciones disponibles");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setText("- Agregar empleado");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setText("- Agregar pago");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setText("- Constancia de sueldo");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel8.setText("- Constancia de renta");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel9.setText("- Boletas de pago");

        javax.swing.GroupLayout dashPaneLayout = new javax.swing.GroupLayout(dashPane);
        dashPane.setLayout(dashPaneLayout);
        dashPaneLayout.setHorizontalGroup(
            dashPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashPaneLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(dashPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(dashPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dashPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        dashPaneLayout.setVerticalGroup(
            dashPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashPaneLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("Dashboard", dashPane);

        plantillaPatronalPane.setBackground(new java.awt.Color(255, 255, 255));

        nit_input.setForeground(new java.awt.Color(102, 102, 102));
        nit_input.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        nit_input.setLabelText("NIT");

        btn_limpiarDatos1.setBackground(new java.awt.Color(255, 102, 102));
        btn_limpiarDatos1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btn_limpiarDatos1.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiarDatos1.setText("Limpiar datos");
        btn_limpiarDatos1.setBorder(null);
        btn_limpiarDatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarDatos1ActionPerformed(evt);
            }
        });

        btn_generarPDF1.setBackground(new java.awt.Color(153, 153, 255));
        btn_generarPDF1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btn_generarPDF1.setForeground(new java.awt.Color(255, 255, 255));
        btn_generarPDF1.setText("Generar PDF");
        btn_generarPDF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarPDF1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plantillaPatronalPaneLayout = new javax.swing.GroupLayout(plantillaPatronalPane);
        plantillaPatronalPane.setLayout(plantillaPatronalPaneLayout);
        plantillaPatronalPaneLayout.setHorizontalGroup(
            plantillaPatronalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plantillaPatronalPaneLayout.createSequentialGroup()
                .addGroup(plantillaPatronalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(plantillaPatronalPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_generarPDF1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(btn_limpiarDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plantillaPatronalPaneLayout.createSequentialGroup()
                        .addComponent(nit_input, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        plantillaPatronalPaneLayout.setVerticalGroup(
            plantillaPatronalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plantillaPatronalPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nit_input, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(plantillaPatronalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpiarDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_generarPDF1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("Planilla Patronal", plantillaPatronalPane);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/logo-UNICAES-png.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(materialTabbed1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(materialTabbed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limpiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarDatosActionPerformed
       
    }//GEN-LAST:event_btn_limpiarDatosActionPerformed

    private void btn_generarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarPDFActionPerformed
        
    }//GEN-LAST:event_btn_generarPDFActionPerformed

    private void btn_limpiarDatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarDatos1ActionPerformed
    this.nit_input.setText("");
    }//GEN-LAST:event_btn_limpiarDatos1ActionPerformed

    private void btn_generarPDF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarPDF1ActionPerformed
        String nit = this.nit_input.getText();
        if (nit.length() == 17) {
            this.genenrar_pdf(nit);
        }
        else{
            JOptionPane.showMessageDialog(null, "Error en el nit");
        }
    }//GEN-LAST:event_btn_generarPDF1ActionPerformed

    public void genenrar_pdf(String pnit){
        conn.Conexion();        
        JasperReport reporte;
        int band = 0;
        
        try {
            rs = this.conn.consulta_impuesto(sc.buscar_empleado(), pnit);
            while (rs.next()) {
                band++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al buscar en la base de datos");
        }
        
        
        if (band > 0) {
            try {
                Map parametro = new HashMap();
                parametro.put("pnit", pnit);

                reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/reportPatronal.jasper"));

                JasperPrint printreport = JasperFillManager.fillReport(reporte, parametro, conn.conex);
                JasperViewer view = new JasperViewer(printreport, false);
                view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                view.setVisible(true);
                 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No se encontró el empleado");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generarPDF;
    private javax.swing.JButton btn_generarPDF1;
    private javax.swing.JButton btn_limpiarDatos;
    private javax.swing.JButton btn_limpiarDatos1;
    private javax.swing.JPanel dashPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private Helpers.MaterialTabbed materialTabbed1;
    private Helpers.TextField nit_input;
    private javax.swing.JPanel plantillaPatronalPane;
    // End of variables declaration//GEN-END:variables
}
